---
title: "Lecture 2 - Data Visualization using ggplot"
output: html_notebook
---
## Class notes
Book chapters differ from online chapters (see online and convert)
Lectures also available asynchronous

## ggplot
General format: 
gplot(data = *data*) + 
  *geom function*(mapping = aes(*mappings*),
    stat = *stat*, position = *position*) + 
    *coordinate function* + 
    *scale function* + 
    *theme function* + 
    *facet function* + *...*

To get nice color palettes, look at RColorBrewer

```{r}
library(RColorBrewer)
display.brewer.all(colorblindFriendly = TRUE)

# Examples using ggplot Theme Assistant
# addins --> ggplot theme assistnat when highlighted graph
library(tidyverse)
p1 <- ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
library(ggplotAssist)
p1 
```

Another good resource: R Graph Gallery


## Coding notes
glimpse(*df*) - shows variables, obs, types, etc.

GGally::ggpairs() - plots correlations bw all variables
  Shows distribution of data for each variable (in same-same category)
  Lower plots show scatterplots
  Corr coefficients in upper plots

In facet_wrap(scales = 'free') lets you have all dif scales
  Can also use 'free_x' or 'free_y' to allow one var to be free and the   other fixed

Patchwork package allows for piecing of multiple plots (or photos or both)

coolors.co to make colors that match photos, can check if colorblind friendly 




